### ISSUE TITLE
macOS installing problem

### ISSUE THREAD

**Issue by bohd4nx** [bohd4nx/coinprice#2]
The problem: 

```bash
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/price", line 5, in <module>
    from coinprice.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/coinprice/main.py", line 2, in <module>
    from coinprice.app.tracker import track_prices
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/coinprice/app/tracker.py", line 8, in <module>
    from coinprice.api import binance, coinbase, bitfinex, kucoin, gateio, kraken, huobi, okx
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/coinprice/api/binance.py", line 1, in <module>
    import requests
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/utils.py", line 30, in <module>
    from .cookies import RequestsCookieJar, cookiejar_from_dict
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/cookies.py", line 159, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

How to fix: 

```python 
pip3 install --upgrade requests
```

Than:

```python 
pip3 install argparse
```

**Also, make sure your installed rich.**

```python 
pip3 install rich
```

_**Problem will be fixed in new, `1.5.4` release**_

**Comment by bohd4nx** [comment]
![image](https://github.com/user-attachments/assets/6ea586f7-dc15-4f76-8b34-ba654232e999)


Released fixed version.

If you still encounter the problem, open an issue or use the command:

```python 
pip3 install --upgrade requests
```
